sudo: false

language: go

go:
  - 1.11

os:
  - linux
  - osx

git:
  depth: 1

install: true

before_script:
  - go get -t

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled
