language: bash
sudo: false
env:
  - TEST=1
branches:
  only:
  - master
  - hotfix
  - release
  - develop
  - feature/.*
script:
    - make test
after_success:
  - APP_VERSION="$(cat VERSION)"
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then APP_VERSION="latest"; fi;
  - mkdir -p dist/
  - cp ./schmokin_install dist/
  - cp ./schmokin dist/
  - cp -r ./libs dist/
  - cd dist && tar -czvf schmokin.tar.gz libs/ schmokin
  - sha1sum schmokin > dist/schmokin.sha1
  - sed -i "s/0.1.0/\"$(cat VERSION)\"/g" dist/schmokin
  - sed -i "s/CHECKSUM_HERE/\"$(sha1sum schmokin | cut -d ' ' -f1)\"/g" dist/schmokin
  - curl -L https://github.com/tcnksm/ghr/releases/download/v0.10.1/ghr_v0.10.1_linux_amd64.tar.gz | tar xz
  - ./ghr_v0.10.1_linux_amd64/ghr --delete --username reaandrew --token $GITHUB_TOKEN "$APP_VERSION" dist/
