language: bash
sudo: false
branches:
  only:
  - master
  - hotfix
  - release
  - develop
  - feature/.*
stages:
  - test
  - package
  - name: deploy_latest
    if: branch = develop
  - name: deploy_master
	if: branch = master
jobs:
    include:
		- stage: package
		  script:
			- mkdir -p dist/
			- cp ./schmokin_install dist/
			- cp ./schmokin dist/
			- sha1sum schmokin > dist/schmokin.sha1
			- sed -i "s/0.1.0/\"$(cat VERSION)\"/g" dist/schmokin
			- sed -i "s/CHECKSUM_HERE/\"$(sha1sum schmokin | cut -d ' ' -f1)\"/g" dist/schmokin
			- curl -L https://github.com/tcnksm/ghr/releases/download/v0.10.1/ghr_v0.10.1_linux_amd64.tar.gz | tar xz
        - stage: deploy_latest
		  script:
      		- ./ghr_v0.10.1_linux_amd64/ghr --delete --username reaandrew --token $GITHUB_TOKEN latest dist/
        - stage: deploy_master
		  script:
      		- ./ghr_v0.10.1_linux_amd64/ghr --username reaandrew --token $GITHUB_TOKEN $(cat VERSION) dist/
