# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/reaandrew/schmokin
    steps:
      - checkout
      - run: make install-deps
      - run: make install-deploy-deps
      - run: make lint
      - run: make test
      - run: make cross-platform-compile
