# <repo>/.github/workflows/main.yml
name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Test
      run: make test
    - name: Compress
      run: make compress
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: |
          ./schmokin.tar.gz
          ./schmokin_install
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: result
          path: ./artifacts
      - name: List
        run: find ./artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*
