# <repo>/.github/workflows/main.yml
name: CI

on: [push]

jobs:
  basic:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Test
      run: make test
    - name: Compress
      run: make compress
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: |
          ./schmokin.tar.gz
          ./schmokin_install
