# <repo>/.github/workflows/main.yml
name: CI

on: [push]

jobs:
  basic:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Test
      run: make test
